# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TATSwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'TATMediaSDK', '~> 3.0.8.2'
  # Pods for TATSwiftDemo

end
